### ISSUE TITLE
Another highlights glitch

### ISSUE THREAD

**Issue by eddic** [LuminanceHDR/LuminanceHDR#210]
I'm having one of those highlights artifact issues that seem to crop up every now and again. My version is 2.6.0 and the raw files can be downloaded at <https://files.isatec.ca/luminance-bug.zip>.

![1024](https://user-images.githubusercontent.com/58451/67807855-31717d80-fa5b-11e9-8346-afc47b482912.jpg)

Thanks for the great project!

**Comment by Froleatric** [comment]
I have this problem, too. It seems to occur if the darkest image in the series has overexposed areas. Only shows up with Debevec, it works with Robertson.

**Comment by fcomida** [comment]
@eddic  @Froleatric Indeed removing oversaturated pixels from the darkest image fix this issue
![debevec_bug](https://user-images.githubusercontent.com/11018726/94479486-2841e100-01d5-11eb-838f-b0038b15cf36.png)

![0007a-0007f_pregamma_1_mantiuk08_auto_luminance_color_saturation_1 38_contrast_enhancement_1_postsaturation_1_postgamma_1](https://user-images.githubusercontent.com/11018726/94479707-7b1b9880-01d5-11eb-8845-1d5a3bdcf439.jpg)

**Comment by fcomida** [comment]
![debevec_bad](https://user-images.githubusercontent.com/11018726/94542277-e488bf00-0248-11eb-9053-6773ea47be64.png)
OLD
![debevec_good](https://user-images.githubusercontent.com/11018726/94542283-e6528280-0248-11eb-992f-8f0d6880eabf.png)
NEW
![debevec_bad_2](https://user-images.githubusercontent.com/11018726/94542279-e5b9ec00-0248-11eb-9864-3198b7352d0a.png)
OLD
![debevec_good_2](https://user-images.githubusercontent.com/11018726/94542285-e6eb1900-0248-11eb-975d-d053d9e91068.png)
NEW
![debevec_bad_3](https://user-images.githubusercontent.com/11018726/94542282-e5b9ec00-0248-11eb-9520-250378b0588e.png)
OLD
![debevec_good_3](https://user-images.githubusercontent.com/11018726/94542287-e783af80-0248-11eb-9221-4c93c02638ed.png)
NEW

**Comment by bash0** [comment]
This issue is solved in commit #09bed861e7b8992a49feecd9995c01d6c5152140.

**Comment by DrLex0** [comment]
Current master has made Robertson actually usable, and I suspect it's due to this pull request #233. I never used Robertson before, because it would produce glitches pretty much every time and was especially bad on dark images, with splotches of brightly colored pixels everywhere.
It would be nice to have presets for Robertson in the HDR Creation Wizard.

However, with **Debevec** I still get the dark stains in over-exposed areas, as well as white stains if the brightest image has pixels with 0,0,0 RGB values. The following synthetic example demonstrates both problems. [Debevec-source-files.zip](https://github.com/LuminanceHDR/LuminanceHDR/files/10050410/Debevec-source-files.zip)

Can a similar fix as was done for Robertson be applied to the Debevec routines?
 
![Debevec](https://user-images.githubusercontent.com/16401844/202919515-5ac79b9f-ff1d-4eb6-a6da-b22467ffb88f.jpg)

As you can see, Robertson now handles this like a champ:
![Robertson](https://user-images.githubusercontent.com/16401844/202919527-1b62450c-cc20-443e-87c7-7a1f969e683f.jpg)

… while the 2.6.0 Robertson had pretty much the same problems as the current Debevec, which makes me believe that it can be fixed in a similar manner:

![Robertson260](https://user-images.githubusercontent.com/16401844/202919879-e216aef6-b96b-480d-b403-6077fe50bc27.jpg)

And if you're now thinking about replying: “just use Robertson all the time”: I want to have the option to use both, because I have noticed Robertson produces different colors which I don't always like.

**Comment by DrLex0** [comment]
Pull request #263 adds the same fix as #233 to Debevec and fixes both the over- and under-exposure problems.

![Example4-after](https://user-images.githubusercontent.com/16401844/204927222-48f9cf5d-19f7-4f95-85e9-b9d72d0c7f55.jpg)
